### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Korben00** [DinoMan/speech-driven-animation#33]
Hello
i have an issue

Here is my code in test.py
```
import sda
va = sda.VideoAnimator(gpu=0)
vid,aud = va("example/image.bmp","example/audio.wav")
va.save_video(vid, aud, "/home/me/speech-driven-animation/video.mp4")
```

When i launch it, i have the error : 
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    va = sda.VideoAnimator(gpu=0)
  File "/home/me/speech-driven-animation/sda/sda.py", line 109, in __init__
    model_dict = torch.load(model_path, map_location=lambda storage, loc: storage.cuda(gpu))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 534, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 697, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

I read that the pickle error was because of git-lfs. But when i git lfs your repository, i have this : 

```
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
Cloning into 'speech-driven-animation'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 143 (delta 0), reused 0 (delta 0), pack-reused 140
Receiving objects: 100% (143/143), 1.21 MiB | 2.50 MiB/s, done.
Resolving deltas: 100% (79/79), done.
Git LFS: (0 of 3 files) 0 B / 632.79 MB
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/DinoMan/speech-driven-animation.git/info/lfs'
```

Have you an idea ?

Thank you

**Comment by Korben00** [comment]
Ok, i found the models here 
https://drive.google.com/open?id=1pJdsnknLmMLvA8RQIAV3AQH8vU0FeK16

Thank you
