### ISSUE TITLE
No module named torchvision

### ISSUE THREAD

**Issue by hydekick** [DinoMan/speech-driven-animation#46]
I just tried my own test code.

```
$ cat test.py
import sda
va = sda.VideoAnimator(gpu=0, model_path="crema")# Instantiate the animator
vid, aud = va("example/audio.bmp", "example/audio.wav")

$ python test.py
Traceback (most recent call last):
File "test.py", line 1, in <module>
  import sda
File "/Users/xxx/speech-driven-animation/sda/__init__.py", line 1, in <module>
  from .sda import VideoAnimator, get_audio_feature_extractor, cut_audio_sequence
File "/Users/xxx/speech-driven-animation/sda/sda.py", line 1, in <module>
  from torchvision import transforms
ImportError: No module named torchvision
```

Could you guess why?
Btw I've already install torchvision 0.5.0

**Comment by NathanKolpa** [comment]
I'm having the same issue

**Comment by AllOverRS** [comment]
Try installing torchvision using command provided on https://pytorch.org/get-started/locally/

Make sure all of your modules are in the same directory and that your python install is set up properly.
