### ISSUE TITLE
problem: torch.load & pickle. help!!!

### ISSUE THREAD

**Issue by ixNeo** [DinoMan/speech-driven-animation#51]
Traceback (most recent call last):
  File "/Users/coolinear/Desktop/pyproj/speech-driven-animation-master/mess.py", line 2, in <module>
    va = sda.VideoAnimator(gpu=-1)# Instantiate the animator
  File "/Users/coolinear/Desktop/pyproj/speech-driven-animation-master/sda/sda.py", line 106, in __init__
    model_dict = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/Users/coolinear/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/coolinear/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by YTMartian** [comment]
download model from README, here: https://drive.google.com/open?id=1pJdsnknLmMLvA8RQIAV3AQH8vU0FeK16

**Comment by AllOverRS** [comment]
> download model from README, here: https://drive.google.com/open?id=1pJdsnknLmMLvA8RQIAV3AQH8vU0FeK16

And make sure you put the models in the `sda\data` folder where there are existing empty placeholder .dat files.

**Comment by NelsonScott** [comment]
Think the new location is here https://drive.google.com/drive/folders/17Dc2keVoNSrlrOdLL3kXdM8wjb20zkbF
