### ISSUE TITLE
Missing version of dependencies in setup.py

### ISSUE THREAD

**Issue by giorgiop** [DinoMan/speech-driven-animation#64]
Can you please provide the version of each dependency in `setup.py` ?

**Comment by DinoMan** [comment]
I left them out because the library should work with most versions of the dependencies. Some people can use the models as feature extractors so I wanted them to be able to use whatever version they wanted. Is something dependency not working for you?

**Comment by bachelorY** [comment]
Hello! I download your code, run the `pip install .`  I successfully installed all dependence, but when I run the Example with Image and Audio Paths, I got some error like this:
```
Traceback (most recent call last):
  File "d:/Program1/python/ai/sda/speech-driven-animation-master/test.py", line 2, in <module>
    va = sda.VideoAnimator(gpu=0, model_path="crema")# Instantiate the animator
  File "d:\Program1\python\ai\sda\speech-driven-animation-master\sda\sda.py", line 109, in __init__
    model_dict = torch.load(model_path, map_location=lambda storage, loc: storage.cuda(gpu))
  File "C:\Users\freest0ne\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 713, in load        
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\freest0ne\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by bachelorY** [comment]
should i run this in linux?

**Comment by bachelorY** [comment]
Sorry, I forgot to replace files in data, it's has fixed

**Comment by DinoMan** [comment]
Yes I have only tested the code on linux so I don't know if there are any issues on windows.
